name: CI - Build and Test Dockerfile

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'run.sh'
      - 'master_api.conf'
      - 'SETUP.md'
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'run.sh'
      - 'master_api.conf'
      - 'SETUP.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman gpg
        podman --version
        podman system info

    - name: Create mock persistence directories for testing
      run: |
        mkdir -p mock_data/{keys,cache,files,pillar}
        sudo chown -R 1000:1000 mock_data

    - name: Build Docker image
      run: |
        podman build -t salt-master-suse:3007.0 -f Dockerfile .
        echo "Build successful!"

    - name: Test container startup
      run: |
        podman run -d --name test-salt-master \
          -p 10022:22 \
          -p 4505:4505 \
          -p 4506:4506 \
          -p 8000:8000 \
          -v $(pwd)/mock_data/keys:/etc/salt/pki/master:Z \
          -v $(pwd)/mock_data/cache:/var/cache/salt/master:Z \
          -v $(pwd)/mock_data/files:/srv/salt:Z \
          -v $(pwd)/mock_data/pillar:/srv/pillar:Z \
          salt-master-suse:3007.0
        sleep 20  # Aguarda inicialização
        podman ps -a
        podman logs test-salt-master | tail -n 20
        # Testes básicos
        nc -zv localhost 10022 || echo "SSH port check failed"
        curl -s http://localhost:8000 || echo "API check failed"
        podman stop test-salt-master
        podman rm test-salt-master
        echo "Test completed!"
